"""The Linux package manifest: what each target calls a tool, or why it has none.

Unlike the Brewfile, this file is *authored* -- it records a decision no machine
can be asked for. It is also generated: every edit rewrites it whole, from the
header below and one table per entry, so the shape of the file is this module's
and not something to be maintained by hand.

Reading needs only the standard library, so the test harness can do it without
uv. That still means Python 3.11, because ``tomllib`` arrived there; this family
is 3.11+ throughout for the same reason. Writing needs ``tomlkit``, which is why
the command runs under uv -- that import is guarded, so importing this module
never requires it.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path

# Sorted below the block above because ruff's isort targets Python 3.9 -- the
# floor the gitwt library must hold to -- and so files tomllib, new in 3.11, as
# third-party. This family needs 3.11 either way; uv supplies it.
import tomllib
from chezpkg_brew import Brewfile
from chezpkg_run import PackagesError

try:
    import tomlkit
except ImportError:
    tomlkit = None

# Written in this order. A field outside this list is kept, sorted, after these
# rather than dropped: `problems()` below is what reports it, and this module
# must not destroy what it does not understand.
FIELDS = ("brew", "apt", "fedora", "el", "mise", "mise_exe", "repo", "note")
# Where an entry can install a tool. One naming none of these installs nowhere,
# which is the deliberate case that `note` has to explain.
TARGETS = frozenset({"apt", "fedora", "el", "mise"})
# `repo` covers gh and starship, which the 01 script installs from their own
# repository and installer because no base repo has them.
KNOWN = TARGETS | {"brew", "mise_exe", "repo", "note"}

HEADER = (
    "Cross-OS package manifest -- what gets installed, and what does not.",
    "",
    "macOS installs from private_dot_config/Brewfile, which is a dump of what",
    "this Mac has. This file maps each of those onto its Linux equivalent so the",
    "Linux profiles stay in step, and records the reason for every one that is",
    "deliberately not ported.",
    "",
    "THE RULE: if a tool is not in the system's package manager, it is not",
    "installed. No release downloads, no vendored installers. The only exceptions",
    "are gh and starship, which the 01 script installs from their own repo and",
    "installer because neither is in any base repo.",
    "",
    "Targets:",
    "  apt     Debian / Ubuntu / Pop!_OS",
    "  fedora  Fedora",
    "  el      RHEL rebuilds (Rocky / Alma / CentOS Stream 9) with EPEL + CRB",
    "  mise    the rootless no-sudo profile, where mise IS the package manager --",
    "          so a tool can be mise-only, available there and nowhere else",
    "",
    "  mise_exe  the binary mise installs, when it differs from the tool name",
    "  repo      installed from its own repository by the 01 script (gh, starship)",
    "",
    'A missing field means "not available on that target": the name is left out',
    "of that distro's install list. An entry naming NO target is not installed on",
    "Linux at all, and then `note` has to say why. That is the whole mechanism",
    "for skipping a tool: there is no separate table.",
    "",
    "GENERATED by `chezmoi-packages` -- see the Packages section of README.md.",
    "Every add and remove rewrites this file from the command's own header, so a",
    "comment added by hand will not survive. Annotations belong in `note`.",
)


@dataclass(frozen=True)
class Manifest:
    """The ``[packages]`` table, and the file it came from."""

    path: Path
    packages: dict[str, dict[str, str]]

    @classmethod
    def read(cls, path: Path) -> Manifest:
        """Read the manifest.

        Args:
            path: The manifest's path.

        Returns:
            Its ``[packages]`` table.

        Raises:
            PackagesError: If the file cannot be read or is not valid TOML.

        """
        try:
            parsed = tomllib.loads(path.read_text(encoding="utf-8"))
        except OSError as exc:
            message = f"cannot read {path}: {exc}"
            raise PackagesError(message) from exc
        except tomllib.TOMLDecodeError as exc:
            message = f"{path} is not valid TOML: {exc}"
            raise PackagesError(message) from exc

        return cls(path, parsed.get("packages", {}))

    def added(self, name: str, fields: dict[str, str]) -> Manifest:
        """Add or replace one entry.

        Args:
            name: The tool's manifest key.
            fields: Its fields.

        Returns:
            A manifest with that entry, leaving this one untouched.

        """
        return replace(self, packages={**self.packages, name: fields})

    def removed(self, name: str) -> Manifest:
        """Drop one entry.

        Args:
            name: The tool's manifest key.

        Returns:
            A manifest without that entry, leaving this one untouched.

        Raises:
            PackagesError: If no entry has that name.

        """
        if name not in self.packages:
            message = f"{name} is not in the manifest"
            raise PackagesError(message)

        return replace(self, packages={k: v for k, v in self.packages.items() if k != name})

    def formula(self, name: str) -> str:
        """Find the Homebrew formula an entry installs.

        Args:
            name: The tool's manifest key.

        Returns:
            Its ``brew`` field, defaulting to the key itself.

        """
        return self.packages.get(name, {}).get("brew", name)

    def render(self) -> str:
        """Render the whole manifest.

        Every quoting and escaping decision is tomlkit's; this only chooses the
        order -- entries alphabetical, fields as in ``FIELDS``.

        Returns:
            The manifest as text.

        Raises:
            PackagesError: If tomlkit is not importable, which means the command
                is not running under uv.

        """
        if tomlkit is None:
            message = (
                "writing the manifest needs tomlkit, which the stdlib has no "
                "equivalent of. Run chezmoi-packages through uv (its shebang "
                "does this), or install the distribution's python3-tomlkit"
            )
            raise PackagesError(message)

        doc = tomlkit.document()
        for line in HEADER:
            doc.add(tomlkit.comment(line))
        doc.add(tomlkit.nl())

        packages = tomlkit.table(is_super_table=True)
        for name in sorted(self.packages):
            fields = self.packages[name]
            entry = tomlkit.table()
            for field in [f for f in FIELDS if f in fields] + sorted(fields.keys() - set(FIELDS)):
                entry[field] = fields[field]
            packages.append(name, entry)
        doc["packages"] = packages

        return tomlkit.dumps(doc)

    def save(self) -> None:
        """Write the manifest, but only once it reads back as what was asked for.

        Raises:
            PackagesError: If the rendered manifest parses to anything other than
                these entries. The file is left untouched.

        """
        text = self.render()

        try:
            back = tomllib.loads(text)
        except tomllib.TOMLDecodeError as exc:
            message = f"refusing to write invalid TOML: {exc}"
            raise PackagesError(message) from exc

        if back.get("packages") != self.packages:
            message = "refusing to write: the rendered manifest does not read back as intended"
            raise PackagesError(message)

        self.path.write_text(text, encoding="utf-8")

    def problems(self, brewfile: Brewfile) -> list[str]:
        """Compare the manifest against the Brewfile and check it is self-consistent.

        The one description of what it means for the two files to agree, shared
        by the ``dump`` report and by ``tests/check.py``.

        Args:
            brewfile: The Brewfile to compare against.

        Returns:
            One human-readable line per problem, empty when the two agree.

        """
        claimed = {e["brew"]: n for n, e in self.packages.items() if "brew" in e}
        declared = brewfile.accountable

        problems = [
            f"{name}: in the Brewfile, unaccounted for in the manifest"
            for name in sorted(declared - claimed.keys())
        ]
        problems += [
            f"{owner}: claims the formula {name!r}, which the Brewfile no longer has"
            for name, owner in sorted(claimed.items())
            if name not in declared
        ]
        problems += [
            f"{name}: installs nowhere and says no reason -- name a target, or add a note"
            for name, entry in sorted(self.packages.items())
            if not TARGETS & entry.keys() and "repo" not in entry and "note" not in entry
        ]
        problems += [
            f"{name}: unknown field(s) {', '.join(sorted(entry.keys() - KNOWN))}"
            for name, entry in sorted(self.packages.items())
            if entry.keys() - KNOWN
        ]
        problems += self._mise_clashes()

        return problems

    def _mise_clashes(self) -> list[str]:
        """Find two entries claiming one mise tool.

        The mise names all land in one generated ``[tools]`` table, where a
        repeat is a TOML error that would break the no-sudo profile's config.

        Returns:
            One line per clash.

        """
        owner: dict[str, str] = {}
        clashes = []
        for name, entry in sorted(self.packages.items()):
            tool = entry.get("mise")
            if tool is None:
                continue
            if tool in owner:
                clashes.append(f"{name}: mise tool {tool!r} already claimed by {owner[tool]}")
            owner.setdefault(tool, name)

        return clashes
